IF OBJECT_ID(N'[__EFMigrationsHistory]') IS NULL
BEGIN
    CREATE TABLE [__EFMigrationsHistory] (
        [MigrationId] nvarchar(150) NOT NULL,
        [ProductVersion] nvarchar(32) NOT NULL,
        CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY ([MigrationId])
    );
END;
GO

BEGIN TRANSACTION;
GO

CREATE TABLE [KHACH] (
    [MAKH] nchar(7) NOT NULL,
    [TENKH] nvarchar(30) NOT NULL,
    [TUOI] int NOT NULL,
    [TEL] nvarchar(12) NOT NULL,
    [DIACHIKH] nvarchar(100) NULL,
    [CMNDKH] nvarchar(15) NOT NULL,
    [LOAIKHACH] nchar(10) NOT NULL,
    CONSTRAINT [PK_KHACH] PRIMARY KEY ([MAKH])
);
GO

CREATE TABLE [NHANVIEN] (
    [MANV] nchar(7) NOT NULL,
    [HOTEN] nvarchar(30) NULL,
    [PHAI] nchar(3) NULL,
    [NGAYSINH] date NULL,
    [SDT] nvarchar(12) NULL,
    [EMAIL] nvarchar(100) NULL,
    [DIACHI] nvarchar(100) NULL,
    CONSTRAINT [PK_NHANVIEN] PRIMARY KEY ([MANV])
);
GO

CREATE TABLE [PHONG] (
    [MAP] int NOT NULL,
    [TENPHONG] nvarchar(30) NOT NULL,
    [LOAI] nvarchar(30) NOT NULL,
    [DONGIA] int NOT NULL,
    [TINHTRANG] bit NOT NULL,
    [GHICHU] text NULL,
    CONSTRAINT [PK_PHONG] PRIMARY KEY ([MAP])
);
GO

CREATE TABLE [PHIEUTHUE] (
    [MAPT] nchar(7) NOT NULL,
    [NGAYLAPPT] date NOT NULL,
    [MAKH] nchar(7) NOT NULL,
    [MAP] int NOT NULL,
    CONSTRAINT [PK_Table_1] PRIMARY KEY ([MAPT]),
    CONSTRAINT [FK_PHIEUTHUE_KHACH] FOREIGN KEY ([MAKH]) REFERENCES [KHACH] ([MAKH]),
    CONSTRAINT [FK_PHIEUTHUE_PHONG] FOREIGN KEY ([MAP]) REFERENCES [PHONG] ([MAP])
);
GO

CREATE TABLE [HOADON] (
    [MAHD] nchar(7) NOT NULL,
    [SONGAYO] int NULL,
    [MANV] nchar(7) NULL,
    [TONGTIEN] int NULL,
    [MAPT] nchar(7) NULL,
    [MAKH] nchar(7) NULL,
    CONSTRAINT [PK_HOADON] PRIMARY KEY ([MAHD]),
    CONSTRAINT [FK_HOADON_KHACH] FOREIGN KEY ([MAKH]) REFERENCES [KHACH] ([MAKH]),
    CONSTRAINT [FK_HOADON_NHANVIEN] FOREIGN KEY ([MANV]) REFERENCES [NHANVIEN] ([MANV]),
    CONSTRAINT [FK_HOADON_PHIEUTHUE] FOREIGN KEY ([MAPT]) REFERENCES [PHIEUTHUE] ([MAPT])
);
GO

CREATE INDEX [IX_HOADON_MAKH] ON [HOADON] ([MAKH]);
GO

CREATE INDEX [IX_HOADON_MANV] ON [HOADON] ([MANV]);
GO

CREATE INDEX [IX_HOADON_MAPT] ON [HOADON] ([MAPT]);
GO

CREATE INDEX [IX_PHIEUTHUE_MAKH] ON [PHIEUTHUE] ([MAKH]);
GO

CREATE INDEX [IX_PHIEUTHUE_MAP] ON [PHIEUTHUE] ([MAP]);
GO

INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
VALUES (N'20231206114236_initialcreate', N'6.0.25');
GO

COMMIT;
GO

