// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Team_Project_4.Models;

#nullable disable

namespace Team_Project_4.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20231206114236_initialcreate")]
    partial class initialcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Team_Project_4.Models.Hoadon", b =>
                {
                    b.Property<string>("Mahd")
                        .HasMaxLength(7)
                        .HasColumnType("nchar(7)")
                        .HasColumnName("MAHD")
                        .IsFixedLength();

                    b.Property<string>("Makh")
                        .HasMaxLength(7)
                        .HasColumnType("nchar(7)")
                        .HasColumnName("MAKH")
                        .IsFixedLength();

                    b.Property<string>("Manv")
                        .HasMaxLength(7)
                        .HasColumnType("nchar(7)")
                        .HasColumnName("MANV")
                        .IsFixedLength();

                    b.Property<string>("Mapt")
                        .HasMaxLength(7)
                        .HasColumnType("nchar(7)")
                        .HasColumnName("MAPT")
                        .IsFixedLength();

                    b.Property<int?>("Songayo")
                        .HasColumnType("int")
                        .HasColumnName("SONGAYO");

                    b.Property<int?>("Tongtien")
                        .HasColumnType("int")
                        .HasColumnName("TONGTIEN");

                    b.HasKey("Mahd");

                    b.HasIndex("Makh");

                    b.HasIndex("Manv");

                    b.HasIndex("Mapt");

                    b.ToTable("HOADON", (string)null);
                });

            modelBuilder.Entity("Team_Project_4.Models.Khach", b =>
                {
                    b.Property<string>("Makh")
                        .HasMaxLength(7)
                        .HasColumnType("nchar(7)")
                        .HasColumnName("MAKH")
                        .IsFixedLength();

                    b.Property<string>("Cmndkh")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("CMNDKH");

                    b.Property<string>("Diachikh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DIACHIKH");

                    b.Property<string>("Loaikhach")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("LOAIKHACH")
                        .IsFixedLength();

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("TEL");

                    b.Property<string>("Tenkh")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TENKH");

                    b.Property<int>("Tuoi")
                        .HasColumnType("int")
                        .HasColumnName("TUOI");

                    b.HasKey("Makh");

                    b.ToTable("KHACH", (string)null);
                });

            modelBuilder.Entity("Team_Project_4.Models.Nhanvien", b =>
                {
                    b.Property<string>("Manv")
                        .HasMaxLength(7)
                        .HasColumnType("nchar(7)")
                        .HasColumnName("MANV")
                        .IsFixedLength();

                    b.Property<string>("Diachi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DIACHI");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Hoten")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("HOTEN");

                    b.Property<DateTime?>("Ngaysinh")
                        .HasColumnType("date")
                        .HasColumnName("NGAYSINH");

                    b.Property<string>("Phai")
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnName("PHAI")
                        .IsFixedLength();

                    b.Property<string>("Sdt")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("SDT");

                    b.HasKey("Manv");

                    b.ToTable("NHANVIEN", (string)null);
                });

            modelBuilder.Entity("Team_Project_4.Models.Phieuthue", b =>
                {
                    b.Property<string>("Mapt")
                        .HasMaxLength(7)
                        .HasColumnType("nchar(7)")
                        .HasColumnName("MAPT")
                        .IsFixedLength();

                    b.Property<string>("Makh")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nchar(7)")
                        .HasColumnName("MAKH")
                        .IsFixedLength();

                    b.Property<int>("Map")
                        .HasColumnType("int")
                        .HasColumnName("MAP");

                    b.Property<DateTime>("Ngaylappt")
                        .HasColumnType("date")
                        .HasColumnName("NGAYLAPPT");

                    b.HasKey("Mapt")
                        .HasName("PK_Table_1");

                    b.HasIndex("Makh");

                    b.HasIndex("Map");

                    b.ToTable("PHIEUTHUE", (string)null);
                });

            modelBuilder.Entity("Team_Project_4.Models.Phong", b =>
                {
                    b.Property<int?>("Map")
                        .HasColumnType("int")
                        .HasColumnName("MAP");

                    b.Property<int>("Dongia")
                        .HasColumnType("int")
                        .HasColumnName("DONGIA");

                    b.Property<string>("Ghichu")
                        .HasColumnType("text")
                        .HasColumnName("GHICHU");

                    b.Property<string>("Loai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("LOAI");

                    b.Property<string>("Tenphong")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TENPHONG");

                    b.Property<bool>("Tinhtrang")
                        .HasColumnType("bit")
                        .HasColumnName("TINHTRANG");

                    b.HasKey("Map");

                    b.ToTable("PHONG", (string)null);
                });

            modelBuilder.Entity("Team_Project_4.Models.Hoadon", b =>
                {
                    b.HasOne("Team_Project_4.Models.Khach", "MakhNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("Makh")
                        .HasConstraintName("FK_HOADON_KHACH");

                    b.HasOne("Team_Project_4.Models.Nhanvien", "ManvNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("Manv")
                        .HasConstraintName("FK_HOADON_NHANVIEN");

                    b.HasOne("Team_Project_4.Models.Phieuthue", "MaptNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("Mapt")
                        .HasConstraintName("FK_HOADON_PHIEUTHUE");

                    b.Navigation("MakhNavigation");

                    b.Navigation("ManvNavigation");

                    b.Navigation("MaptNavigation");
                });

            modelBuilder.Entity("Team_Project_4.Models.Phieuthue", b =>
                {
                    b.HasOne("Team_Project_4.Models.Khach", "MakhNavigation")
                        .WithMany("Phieuthues")
                        .HasForeignKey("Makh")
                        .IsRequired()
                        .HasConstraintName("FK_PHIEUTHUE_KHACH");

                    b.HasOne("Team_Project_4.Models.Phong", "MapNavigation")
                        .WithMany("Phieuthues")
                        .HasForeignKey("Map")
                        .IsRequired()
                        .HasConstraintName("FK_PHIEUTHUE_PHONG");

                    b.Navigation("MakhNavigation");

                    b.Navigation("MapNavigation");
                });

            modelBuilder.Entity("Team_Project_4.Models.Khach", b =>
                {
                    b.Navigation("Hoadons");

                    b.Navigation("Phieuthues");
                });

            modelBuilder.Entity("Team_Project_4.Models.Nhanvien", b =>
                {
                    b.Navigation("Hoadons");
                });

            modelBuilder.Entity("Team_Project_4.Models.Phieuthue", b =>
                {
                    b.Navigation("Hoadons");
                });

            modelBuilder.Entity("Team_Project_4.Models.Phong", b =>
                {
                    b.Navigation("Phieuthues");
                });
#pragma warning restore 612, 618
        }
    }
}
